import logging
import os
import shutil
from datetime import datetime

from sqlalchemy.orm import Session

from ..config import settings
from ..models.ari_user import ARIUser
from ..models.extension import Extension
from ..models.followme import FollowMe
from ..models.ivr import IVR
from ..models.queue import Queue
from ..models.route import InboundRoute, OutboundRoute
from ..models.schedule import Schedule
from ..models.trunk import Trunk
from ..models.voicemail import Voicemail

logger = logging.getLogger(__name__)
CFG = settings.asterisk_config_path
IP = settings.server_ip


def _header(filename: str) -> str:
    return f"; {filename} — generated by Asterisk GUI Manager — {datetime.now()}\n\n"


def _write(filename: str, content: str):
    path = os.path.join(CFG, filename)
    bak = f"{path}.bak.{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    if os.path.exists(path):
        shutil.copy2(path, bak)
    with open(path, "w") as f:
        f.write(content)
    logger.info(f"Written: {filename}")


def _dest(dest_type: str, dest_id: str) -> str:
    if dest_type == "extension":
        return f"Dial(PJSIP/{dest_id},30,rT)"
    if dest_type == "queue":
        return f"Queue({dest_id},t,,60)"
    if dest_type == "ivr":
        return f"Goto(ivr-{dest_id},s,1)"
    if dest_type == "voicemail":
        return f"VoiceMail({dest_id}@default,u)"
    return "Hangup()"


# ─── pjsip.conf ──────────────────────────────────────────────────────────────

def gen_pjsip(db: Session) -> str:
    lines = [
        _header("pjsip.conf"),
        "[global]",
        "type=global",
        "endpoint_identifier_order=username,ip,anonymous",
        "default_realm=asterisk",
        "",
        "[transport-udp]",
        "type=transport",
        "protocol=udp",
        "bind=0.0.0.0:5060",
        f"external_media_address={IP}",
        f"external_signaling_address={IP}",
        "local_net=172.16.0.0/12",
        "local_net=10.0.0.0/8",
        "",
        "[transport-tcp]",
        "type=transport",
        "protocol=tcp",
        "bind=0.0.0.0:5060",
        "",
        "[transport-wss]",
        "type=transport",
        "protocol=wss",
        "bind=0.0.0.0:8089",
        "",
    ]

    for ext in db.query(Extension).filter(Extension.is_active == True).all():
        codecs = [c.strip() for c in (ext.codecs or "ulaw,alaw").split(",")]
        cid = ext.callerid or ext.name

        if ext.type == "webrtc":
            lines += [
                f"[{ext.number}]",
                "type=endpoint",
                "context=from-internal",
                "disallow=all",
            ] + [f"allow={c}" for c in codecs] + [
                f"auth={ext.number}-auth",
                f"aors={ext.number}",
                "transport=transport-wss",
                "use_avpf=yes",
                "media_encryption=dtls",
                "dtls_auto_generate_cert=yes",
                "dtls_verify=fingerprint",
                "dtls_setup=actpass",
                "ice_support=yes",
                "rtcp_mux=yes",
                "rtp_symmetric=yes",
                "force_rport=yes",
                "rewrite_contact=yes",
                "direct_media=no",
                f"callerid={cid} <{ext.number}>",
                f"language={ext.language}",
                "",
                f"[{ext.number}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={ext.number}",
                f"password={ext.password}",
                "realm=asterisk",
                "",
                f"[{ext.number}]",
                "type=aor",
                "max_contacts=1",
                "remove_existing=yes",
                "",
            ]
        else:
            lines += [
                f"[{ext.number}]",
                "type=endpoint",
                "context=from-internal",
                "disallow=all",
            ] + [f"allow={c}" for c in codecs] + [
                f"auth={ext.number}-auth",
                f"aors={ext.number}",
                "rtp_symmetric=yes",
                "force_rport=yes",
                "rewrite_contact=yes",
                "direct_media=no",
                f"callerid={cid} <{ext.number}>",
                f"language={ext.language}",
                "",
                f"[{ext.number}-auth]",
                "type=auth",
                "auth_type=userpass",
                f"username={ext.number}",
                f"password={ext.password}",
                "realm=asterisk",
                "",
                f"[{ext.number}]",
                "type=aor",
                "max_contacts=1",
                "remove_existing=yes",
                "qualify_frequency=30",
                "qualify_timeout=3.0",
                "",
            ]

    for t in db.query(Trunk).filter(Trunk.is_active == True).all():
        codecs = [c.strip() for c in (t.codecs or "ulaw,alaw").split(",")]

        context = t.context_in or "from-trunk"
        # When match_ip=True the trunk is trusted by IP — no auth challenge for REGISTER/INVITE
        # match_ip=True → gateway confiable por IP, sin auth challenge (REGISTER/INVITE)
        # pero mantenemos identify_by=username,ip para que el AOR lookup use el From username
        ep_auth = [] if t.match_ip else [f"auth={t.name}-auth"]
        lines += [
            f"[{t.name}]",
            "type=endpoint",
            f"context={context}",
            "disallow=all",
        ] + [f"allow={c}" for c in codecs] + ep_auth + [
            f"aors={t.name}",
            "rtp_symmetric=yes",
            "force_rport=yes",
            "rewrite_contact=yes",
            f"direct_media={'yes' if t.direct_media else 'no'}",
            "identify_by=username,ip",
            "",
            f"[{t.name}-auth]",
            "type=auth",
            "auth_type=userpass",
            f"username={t.username}",
            f"password={t.password}",
            "realm=asterisk",
            "",
            f"[{t.name}]",
            "type=aor",
            # receive → acepta registro dinámico del gateway; otro modo → contacto estático fijo
            f"max_contacts={'1' if t.registration == 'receive' else '0'}",
        ]
        if t.registration == "receive":
            lines.append("remove_existing=yes")
        else:
            lines.append(f"contact=sip:{t.username}@{t.host}:{t.port}")
        if t.qualify_frequency and t.qualify_frequency > 0:
            lines.append(f"qualify_frequency={t.qualify_frequency}")
        lines.append("")

        if t.registration == "send":
            lines += [
                f"[{t.name}-registration]",
                "type=registration",
                "transport=transport-udp",
                f"outbound_auth={t.name}-auth",
                f"server_uri=sip:{t.host}",
                f"client_uri=sip:{t.username}@{t.host}",
                "retry_interval=60",
                "expiration=3600",
                "",
            ]

        if t.match_ip:
            lines += [
                f"[{t.name}-identify]",
                "type=identify",
                f"endpoint={t.name}",
                f"match={t.host}",
                "",
            ]

    return "\n".join(lines)


# ─── extensions.conf ─────────────────────────────────────────────────────────

def gen_extensions(db: Session) -> str:
    lines = [
        _header("extensions.conf"),
        "[general]",
        "",
        "[globals]",
        "ATTENDED_TRANSFER_COMPLETE_SOUND=beep",
        "",
        "[from-internal]",
    ]

    trunks_map = {t.id: t for t in db.query(Trunk).all()}

    for ext in db.query(Extension).filter(Extension.is_active == True).all():
        lines.append(f"exten => {ext.number},1,NoOp(Llamada a {ext.number})")
        lines.append(f" same => n,GotoIf($[${{BLACKLIST()}}]?blacklisted,1)")
        if ext.recording == "always":
            lines.append(
                f" same => n,MixMonitor(/var/spool/asterisk/monitor/"
                f"${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{CALLERID(num)}}-{ext.number}.wav,b)"
            )
        if ext.followme_enabled:
            lines.append(f" same => n,FollowMe({ext.number})")
        else:
            lines.append(f" same => n,Dial(PJSIP/{ext.number},30,rT)")
        if ext.voicemail_enabled:
            lines.append(f" same => n,VoiceMail({ext.number}@default,u)")
        lines.append(f" same => n,Hangup()")
        lines.append("")

    for route in (
        db.query(OutboundRoute)
        .filter(OutboundRoute.is_active == True)
        .order_by(OutboundRoute.priority)
        .all()
    ):
        trunk = trunks_map.get(route.trunk_id)
        if not trunk:
            continue
        pattern = route.pattern if route.pattern.startswith("_") else f"_{route.pattern}"
        lines.append(f"exten => {pattern},1,NoOp(Salida: {route.name})")
        if route.prefix_remove:
            lines.append(f" same => n,Set(EXTEN=${{EXTEN:{route.prefix_remove}}})")
        if route.prefix_add:
            lines.append(f" same => n,Set(EXTEN={route.prefix_add}${{EXTEN}})")
        if route.recording:
            lines.append(
                f" same => n,MixMonitor(/var/spool/asterisk/monitor/"
                f"${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{CALLERID(num)}}-out.wav,b)"
            )
        lines.append(f" same => n,Dial(PJSIP/${{EXTEN}}@{trunk.name},60,rT)")
        lines.append(f" same => n,Hangup()")
        lines.append("")

    lines += [
        "exten => 700,1,Park()",
        "",
        "exten => *97,1,VoiceMailMain(${CALLERID(num)}@default)",
        " same => n,Hangup()",
        "",
        "exten => blacklisted,1,Answer()",
        " same => n,Playback(ss-noservice)",
        " same => n,Hangup()",
        "",
        "exten => i,1,Playback(invalid)",
        " same => n,Hangup()",
        "exten => t,1,Playback(vm-goodbye)",
        " same => n,Hangup()",
        "",
        "[from-trunk]",
        "exten => s,1,NoOp(Llamada entrante de ${CALLERID(num)})",
        " same => n,Answer()",
        " same => n,Wait(1)",
        " same => n,GotoIf($[${BLACKLIST()}]?blacklisted,1)",
        " same => n,Goto(inbound-did,${EXTEN},1)",
        "exten => _X.,1,Goto(s,1)",
        "exten => blacklisted,1,Playback(ss-noservice)",
        " same => n,Hangup()",
        "",
        "[inbound-did]",
    ]

    for r in db.query(InboundRoute).all():
        pattern = r.did if r.did else "_X."
        lines.append(f"exten => {pattern},1,NoOp(DID {r.did})")
        lines.append(f" same => n,{_dest(r.destination_type, r.destination_id)}")
        lines.append(f" same => n,Hangup()")
        lines.append("")
    lines += ["exten => _X.,1,Answer()", " same => n,Hangup()", ""]

    for ivr in db.query(IVR).all():
        lines.append(f"[ivr-{ivr.id}]")
        lines.append(f"exten => s,1,NoOp(IVR {ivr.name})")
        lines.append(" same => n,Answer()")
        if ivr.welcome_audio:
            lines.append(f" same => n(menu),Background(custom/{ivr.welcome_audio})")
        lines.append(f" same => n,WaitExten({ivr.timeout})")
        lines.append("")
        for opt in ivr.options:
            lines.append(f"exten => {opt.key},1,{_dest(opt.destination_type, opt.destination_id)}")
            lines.append(f" same => n,Hangup()")
            lines.append("")
        lines.append("exten => i,1,Playback(invalid)")
        lines.append(" same => n,Goto(s,menu)")
        lines.append("exten => t,1,Goto(s,menu)")
        lines.append("")

    for sched in db.query(Schedule).all():
        lines.append(f"[horario-{sched.id}]")
        days = sched.days_of_week or "mon-fri"
        lines.append(
            f"exten => s,1,GotoIfTime({sched.open_time}-{sched.close_time},{days},*,*?"
            f"{sched.open_destination},s,1)"
        )
        lines.append(f" same => n,Goto({sched.closed_destination},s,1)")
        lines.append("")

    for fm in db.query(FollowMe).filter(FollowMe.is_active == True).all():
        lines.append(f"[followme-{fm.extension}]")
        lines.append(f"exten => s,1,FollowMe({fm.extension})")
        lines.append(" same => n,Hangup()")
        lines.append("")

    return "\n".join(lines)


# ─── queues.conf ─────────────────────────────────────────────────────────────

def gen_queues(db: Session) -> str:
    lines = [
        _header("queues.conf"),
        "[general]",
        "persistentmembers=yes",
        "autofill=yes",
        "monitor-type=MixMonitor",
        "",
    ]
    for q in db.query(Queue).all():
        lines += [
            f"[{q.name}]",
            f"strategy={q.strategy}",
            f"timeout={q.agent_timeout}",
            f"retry={q.retry}",
            f"wrapuptime={q.wrapup_time}",
            f"maxlen={q.max_callers or 0}",
            f"musicclass={q.music_on_hold}",
            "joinempty=yes",
            "leavewhenempty=no",
            "ringinuse=no",
            f"announce-position={'yes' if q.announce_position else 'no'}",
            f"announce-holdtime={'yes' if q.announce_hold_time else 'no'}",
            f"announce-frequency={q.announce_frequency}",
            "monitor-format=wav",
            "monitor-join=yes",
        ]
        for m in q.members:
            lines.append(f"member => PJSIP/{m.extension},0,{m.extension},{m.penalty}")
        lines.append("")
    return "\n".join(lines)


# ─── voicemail.conf ──────────────────────────────────────────────────────────

def gen_voicemail(db: Session) -> str:
    lines = [
        _header("voicemail.conf"),
        "[general]",
        "format=wav",
        "attach=yes",
        "maxmsg=100",
        "maxsecs=300",
        "minsecs=3",
        "maxlogins=3",
        f"serveremail=asterisk@{IP}",
        "",
        "[default]",
    ]
    for vm in db.query(Voicemail).all():
        lines.append(f"{vm.extension} => {vm.password},{vm.extension},{vm.email or ''}")
    lines.append("")
    return "\n".join(lines)


# ─── followme.conf ───────────────────────────────────────────────────────────

def gen_followme(db: Session) -> str:
    lines = [_header("followme.conf"), "[general]", "takecall=1", "declinecall=2", ""]
    for fm in db.query(FollowMe).filter(FollowMe.is_active == True).all():
        lines += [
            f"[{fm.extension}]",
            "active=yes",
            f"ringtime={fm.initial_ring_time}",
            f"music={fm.music_on_hold}",
            "context=from-internal",
        ]
        if fm.confirm_calls:
            lines.append("confirm=yes")
        lines.append(f"number => {fm.extension},{fm.initial_ring_time},")
        for d in sorted(fm.destinations, key=lambda x: x.order):
            lines.append(f"number => {d.number},{d.timeout},")
        lines.append("")
    return "\n".join(lines)


# ─── ari.conf ────────────────────────────────────────────────────────────────

def gen_ari(db: Session) -> str:
    lines = [_header("ari.conf"), "[general]", "enabled=yes", "pretty=yes", "allowed_origins=*", ""]
    for u in db.query(ARIUser).filter(ARIUser.is_active == True).all():
        lines += [
            f"[{u.username}]",
            "type=user",
            f"read_only={'yes' if u.permissions == 'read_only' else 'no'}",
            "password_format=plain",
            f"password={u.password}",
            "",
        ]
    return "\n".join(lines)


# ─── generate_all ────────────────────────────────────────────────────────────

def generate_all(db: Session):
    for filename, generator in [
        ("pjsip.conf", gen_pjsip),
        ("extensions.conf", gen_extensions),
        ("queues.conf", gen_queues),
        ("voicemail.conf", gen_voicemail),
        ("followme.conf", gen_followme),
        ("ari.conf", gen_ari),
    ]:
        try:
            _write(filename, generator(db))
        except Exception as e:
            logger.error(f"Error generating {filename}: {e}")
            raise
