import logging
import os
import shutil
from datetime import datetime

from sqlalchemy.orm import Session

from ..config import settings
from ..models.ari_user import ARIUser
from ..models.extension import Extension
from ..models.followme import FollowMe
from ..models.ivr import IVR
from ..models.queue import Queue
from ..models.route import InboundRoute, OutboundRoute
from ..models.trunk import Trunk
from ..models.voicemail import Voicemail

logger = logging.getLogger(__name__)
CFG = settings.asterisk_config_path


def _header(filename: str) -> str:
    return f"; {filename} — generated by Asterisk GUI Manager\n; {datetime.now()}\n\n"


def _write(filename: str, content: str):
    path = os.path.join(CFG, filename)
    bak = f"{path}.bak.{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    if os.path.exists(path):
        shutil.copy2(path, bak)
    with open(path, "w") as f:
        f.write(content)
    logger.info(f"Written: {filename}")


def _dest(dest_type: str, dest_id: str) -> str:
    if dest_type == "extension":
        return f"Dial(PJSIP/{dest_id},30,rT)"
    if dest_type == "queue":
        return f"Queue({dest_id})"
    if dest_type == "ivr":
        return f"Goto(ivr-{dest_id},s,1)"
    if dest_type == "voicemail":
        return f"VoiceMail({dest_id}@default,u)"
    return "Hangup()"


# ─── pjsip.conf ──────────────────────────────────────────────────────────────

def gen_pjsip(db: Session) -> str:
    L = [_header("pjsip.conf")]

    L += [
        "[transport-udp]", "type=transport", "protocol=udp", "bind=0.0.0.0", "",
        "[transport-tcp]", "type=transport", "protocol=tcp", "bind=0.0.0.0", "",
        "[transport-wss]", "type=transport", "protocol=wss", "bind=0.0.0.0", "",
    ]

    extensions = db.query(Extension).filter(Extension.is_active == True).all()
    for ext in extensions:
        codecs = [c.strip() for c in (ext.codecs or "ulaw,alaw").split(",")]
        cid = ext.callerid or ext.name

        L += [
            f"[{ext.number}]", "type=aor", "max_contacts=1",
            "remove_existing=yes", "qualify_frequency=60", "",
        ]
        L += [
            f"[{ext.number}]", "type=auth", "auth_type=userpass",
            f"username={ext.number}", f"password={ext.password}", "",
        ]
        ep = [
            f"[{ext.number}]", "type=endpoint",
            f"context={ext.context}", "disallow=all",
        ]
        for c in codecs:
            ep.append(f"allow={c}")
        ep += [f"aors={ext.number}", f"auth={ext.number}",
               f"callerid={cid} <{ext.number}>", f"language={ext.language}"]
        if ext.type == "webrtc":
            ep += [
                "transport=transport-wss", "use_avpf=yes",
                "media_encryption=dtls", "dtls_verify=fingerprint",
                "dtls_setup=actpass", "ice_support=yes",
                "media_use_received_transport=yes", "rtcp_mux=yes",
            ]
        L += ep + [""]

    trunks = db.query(Trunk).filter(Trunk.is_active == True).all()
    for t in trunks:
        codecs = [c.strip() for c in (t.codecs or "ulaw,alaw").split(",")]
        L += [
            f"[{t.name}-auth]", "type=auth", "auth_type=userpass",
            f"username={t.username}", f"password={t.password}", "",
        ]
        L += [
            f"[{t.name}]", "type=aor",
            f"contact=sip:{t.host}:{t.port}",
            f"qualify_frequency={t.qualify_frequency}", "",
        ]
        ep = [
            f"[{t.name}]", "type=endpoint",
            f"context={t.context_in}", "disallow=all",
        ]
        for c in codecs:
            ep.append(f"allow={c}")
        ep += [
            f"outbound_auth={t.name}-auth", f"aors={t.name}",
            f"direct_media={'yes' if t.direct_media else 'no'}",
        ]
        L += ep + [""]

        if t.registration == "send":
            L += [
                f"[{t.name}-reg]", "type=registration", "transport=transport-udp",
                f"outbound_auth={t.name}-auth",
                f"server_uri=sip:{t.host}:{t.port}",
                f"client_uri=sip:{t.username}@{t.host}:{t.port}",
                "retry_interval=60", "expiration=3600", "",
            ]
        if t.match_ip:
            L += [
                f"[{t.name}-match]", "type=identify",
                f"endpoint={t.name}", f"match={t.host}", "",
            ]

    return "\n".join(L)


# ─── extensions.conf ─────────────────────────────────────────────────────────

def gen_extensions(db: Session) -> str:
    L = [_header("extensions.conf"), "[globals]", "ATTENDED_TRANSFER_COMPLETE_SOUND=beep", ""]

    extensions = db.query(Extension).filter(Extension.is_active == True).all()
    trunks_map = {t.id: t for t in db.query(Trunk).all()}
    outbound = (
        db.query(OutboundRoute)
        .filter(OutboundRoute.is_active == True)
        .order_by(OutboundRoute.priority)
        .all()
    )

    L.append("[from-internal]")
    for ext in extensions:
        L.append(f"exten => {ext.number},1,NoOp(Call to {ext.number})")
        L.append(f" same => n,GotoIf($[\"${{BLACKLIST()}}\"=\"1\"]?blocked)")
        if ext.recording == "always":
            L.append(
                f" same => n,MixMonitor(/var/spool/asterisk/monitor/"
                f"${{STRFTIME(${{EPOCH}},,%Y/%m/%d)}}/"
                f"{ext.number}-${{UNIQUEID}}.wav,b)"
            )
        if ext.followme_enabled:
            L.append(f" same => n,FollowMe({ext.number})")
        else:
            L.append(f" same => n,Dial(PJSIP/{ext.number},30,rT)")
        if ext.voicemail_enabled:
            L.append(f" same => n,VoiceMail({ext.number}@default,u)")
        L.append(f" same => n,Hangup()")
        L.append("")

    for route in outbound:
        trunk = trunks_map.get(route.trunk_id)
        if not trunk:
            continue
        L.append(f"exten => {route.pattern},1,NoOp(Outbound: {route.name})")
        if route.prefix_remove:
            L.append(f" same => n,Set(EXTEN=${{EXTEN:{route.prefix_remove}}})")
        if route.prefix_add:
            L.append(f" same => n,Set(EXTEN={route.prefix_add}${{EXTEN}})")
        if route.recording:
            L.append(
                f" same => n,MixMonitor(/var/spool/asterisk/monitor/"
                f"${{STRFTIME(${{EPOCH}},,%Y/%m/%d)}}/out-${{CALLERID(num)}}-${{UNIQUEID}}.wav,b)"
            )
        L.append(f" same => n,Dial(PJSIP/${{EXTEN}}@{trunk.name},60,rT)")
        L.append(f" same => n,Hangup()")
        L.append("")

    L += [
        "exten => i,1,Playback(invalid)", " same => n,Hangup()",
        "exten => t,1,Playback(vm-goodbye)", " same => n,Hangup()",
        "exten => blocked,1,Answer()",
        " same => n,Playback(you-are-blocked)", " same => n,Hangup()", "",
    ]

    L.append("[from-trunk]")
    L.append("exten => _X.,1,NoOp(Incoming)")
    L.append(" same => n,GotoIf($[\"${BLACKLIST()}\"=\"1\"]?blocked)")
    L.append(" same => n,Goto(inbound-did,${EXTEN},1)")
    L.append(" same => n(blocked),Answer()")
    L.append(" same => n,Playback(you-are-blocked)")
    L.append(" same => n,Hangup()")
    L.append("")

    inbound = db.query(InboundRoute).all()
    L.append("[inbound-did]")
    for r in inbound:
        pattern = r.did if r.did else "_X."
        L.append(f"exten => {pattern},1,NoOp(DID {r.did})")
        L.append(f" same => n,{_dest(r.destination_type, r.destination_id)}")
        L.append(f" same => n,Hangup()")
        L.append("")
    L += ["exten => _X.,1,Answer()", " same => n,Hangup()", ""]

    ivrs = db.query(IVR).all()
    for ivr in ivrs:
        ctx = f"ivr-{ivr.id}"
        L.append(f"[{ctx}]")
        L.append("exten => s,1,Answer()")
        L.append(" same => n,Set(IVR_ATTEMPTS=0)")
        if ivr.welcome_audio:
            L.append(f" same => n(menu),Playback({ivr.welcome_audio})")
        L.append(f" same => n,WaitExten({ivr.timeout})")
        L.append("")
        for opt in ivr.options:
            L.append(f"exten => {opt.key},1,{_dest(opt.destination_type, opt.destination_id)}")
            L.append(f" same => n,Hangup()")
            L.append("")
        L.append("exten => i,1,Set(IVR_ATTEMPTS=$[${{IVR_ATTEMPTS}}+1])")
        if ivr.invalid_action == "hangup":
            L.append(" same => n,Hangup()")
        else:
            L.append(f" same => n,GotoIf($[${{IVR_ATTEMPTS}}>={ivr.max_attempts}]?done)")
            L.append(" same => n,Goto(s,menu)")
            L.append(" same => n(done),Hangup()")
        L.append("exten => t,1," + ("Hangup()" if ivr.timeout_action == "hangup" else "Goto(s,menu)"))
        L.append("")

    vms = db.query(Voicemail).all()
    for vm in vms:
        L.append(f"[voicemail-{vm.extension}]")
        L.append("exten => s,1,Answer()")
        L.append(f" same => n,VoiceMail({vm.extension}@default,u)")
        L.append(" same => n,Hangup()")
        L.append("")

    return "\n".join(L)


# ─── queues.conf ─────────────────────────────────────────────────────────────

def gen_queues(db: Session) -> str:
    L = [_header("queues.conf"), "[general]",
         "persistentmembers=yes", "autofill=yes", "monitor-type=MixMonitor", ""]
    for q in db.query(Queue).all():
        L.append(f"[{q.name}]")
        L.append(f"strategy={q.strategy}")
        L.append(f"timeout={q.agent_timeout}")
        L.append(f"retry={q.retry}")
        L.append(f"wrapuptime={q.wrapup_time}")
        if q.max_callers:
            L.append(f"maxlen={q.max_callers}")
        L.append(f"musicclass={q.music_on_hold}")
        L.append(f"announce-position={'yes' if q.announce_position else 'no'}")
        L.append(f"announce-holdtime={'yes' if q.announce_hold_time else 'no'}")
        if q.announce_position or q.announce_hold_time:
            L.append(f"announce-frequency={q.announce_frequency}")
        if q.recording:
            L.append("monitor-format=wav")
        for m in q.members:
            L.append(f"member => PJSIP/{m.extension},{m.penalty}")
        L.append("")
    return "\n".join(L)


# ─── voicemail.conf ──────────────────────────────────────────────────────────

def gen_voicemail(db: Session) -> str:
    L = [_header("voicemail.conf"), "[general]",
         "format=wav49|gsm|wav", "attach=yes", "maxmsg=100",
         "maxsecs=300", "minsecs=3", "maxlogins=3", "",
         "[default]"]
    for vm in db.query(Voicemail).all():
        opts = []
        if vm.attach_audio:
            opts.append("attach=yes")
        if vm.delete_after_email:
            opts.append("deletevoicemail=yes")
        L.append(f"{vm.extension} => {vm.password},{vm.extension},{vm.email or ''},,{'|'.join(opts)}")
    L.append("")
    return "\n".join(L)


# ─── followme.conf ───────────────────────────────────────────────────────────

def gen_followme(db: Session) -> str:
    L = [_header("followme.conf"), "[general]", "takecall=1", "declinecall=2", ""]
    for fm in db.query(FollowMe).filter(FollowMe.is_active == True).all():
        L.append(f"[{fm.extension}]")
        L.append(f"music={fm.music_on_hold}")
        L.append("context=from-internal")
        L.append("enable=yes")
        if fm.confirm_calls:
            L.append("confirm=yes")
        L.append(f"number=>{fm.extension},{fm.initial_ring_time},1")
        for i, d in enumerate(sorted(fm.destinations, key=lambda x: x.order), 2):
            L.append(f"number=>{d.number},{d.timeout},{i}")
        L.append("")
    return "\n".join(L)


# ─── ari.conf ────────────────────────────────────────────────────────────────

def gen_ari(db: Session) -> str:
    L = [_header("ari.conf"), "[general]", "enabled=yes", "pretty=no", "allowed_origins=*", ""]
    for u in db.query(ARIUser).filter(ARIUser.is_active == True).all():
        L.append(f"[{u.username}]")
        L.append("type=user")
        L.append(f"read_only={'yes' if u.permissions == 'read_only' else 'no'}")
        L.append(f"password_format={u.password_format}")
        L.append(f"password={u.password}")
        if u.cors_origins:
            L.append(f"allowed_origins={u.cors_origins}")
        L.append("")
    return "\n".join(L)


# ─── Generate all ────────────────────────────────────────────────────────────

def generate_all(db: Session):
    for filename, generator in [
        ("pjsip.conf", gen_pjsip),
        ("extensions.conf", gen_extensions),
        ("queues.conf", gen_queues),
        ("voicemail.conf", gen_voicemail),
        ("followme.conf", gen_followme),
        ("ari.conf", gen_ari),
    ]:
        try:
            content = generator(db)
            _write(filename, content)
        except Exception as e:
            logger.error(f"Error generating {filename}: {e}")
            raise
